replicaCount: 1
image:
  repository: 010525338060.dkr.ecr.us-west-2.amazonaws.com/fitness-tracker/auth-service
  tag: sha-bd2cef7
serviceAccount:
  roleArn: arn:aws:iam::010525338060:role/LabRole
externalSecrets:
  dbSecretPath: fitness-tracker/dev/auth/db
  jwtSecretPath: fitness-tracker/dev/auth/jwt
