replicaCount: 1
image:
  repository: 010525338060.dkr.ecr.us-west-2.amazonaws.com/fitness-tracker/frontend
  tag: sha-92f4171
ingress:
  host: dev.cs686.live
  annotations:
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-west-2:010525338060:certificate/969a21cf-873e-451b-9be2-faec4907762c
