replicaCount: 2
image:
  repository: 793012580999.dkr.ecr.us-west-2.amazonaws.com/fitness-tracker/analytics-service
  tag: sha-bdfdfdd
serviceAccount:
  roleArn: arn:aws:iam::793012580999:role/LabRole
externalSecrets:
  dbSecretPath: fitness-tracker/dev/analytics/db
  jwtSecretPath: fitness-tracker/dev/auth/jwt
  sqsSecretPath: fitness-tracker/dev/workouts/sqs
