replicaCount: 1
image:
  repository: 793012580999.dkr.ecr.us-west-2.amazonaws.com/fitness-tracker/workouts-service
  tag: sha-7b2e892
serviceAccount:
  roleArn: arn:aws:iam::793012580999:role/LabRole
externalSecrets:
  dbSecretPath: fitness-tracker/dev/workouts/db
  jwtSecretPath: fitness-tracker/dev/auth/jwt
  sqsSecretPath: fitness-tracker/dev/workouts/sqs
