# Per-environment Helm value overrides for dev
# Apply with: helm upgrade --install <release> <chart> -f values/dev.yaml

auth-service:
  replicaCount: 2
  image:
    repository: 793012580999.dkr.ecr.us-west-2.amazonaws.com/fitness-tracker/auth-service
    tag: sha-f384a70
  serviceAccount:
    roleArn: arn:aws:iam::793012580999:role/LabRole
  externalSecrets:
    dbSecretPath: fitness-tracker/dev/auth/db
    jwtSecretPath: fitness-tracker/dev/auth/jwt

workouts-service:
  replicaCount: 2
  image:
    repository: 793012580999.dkr.ecr.us-west-2.amazonaws.com/fitness-tracker/workouts-service
    tag: sha-f384a70
  serviceAccount:
    roleArn: arn:aws:iam::793012580999:role/LabRole
  externalSecrets:
    dbSecretPath: fitness-tracker/dev/workouts/db
    jwtSecretPath: fitness-tracker/dev/auth/jwt
    sqsSecretPath: fitness-tracker/dev/workouts/sqs

analytics-service:
  replicaCount: 2
  image:
    repository: 793012580999.dkr.ecr.us-west-2.amazonaws.com/fitness-tracker/analytics-service
    tag: sha-f384a70
  serviceAccount:
    roleArn: arn:aws:iam::793012580999:role/LabRole
  externalSecrets:
    dbSecretPath: fitness-tracker/dev/analytics/db
    jwtSecretPath: fitness-tracker/dev/auth/jwt
    sqsSecretPath: fitness-tracker/dev/workouts/sqs

frontend:
  replicaCount: 2
  image:
    repository: 793012580999.dkr.ecr.us-west-2.amazonaws.com/fitness-tracker/frontend
    tag: sha-f384a70
  ingress:
    host: dev.cs686.live
